### ISSUE TITLE
New enemy ship designs

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#15]
Create more art for AI ships that the player will encounter.

<If you can, please add detail about what kinds of ships you're going to work on specifically, like pirate ships, federation ships, other ships, etc. If you aren't sure yet, that's okay>

**Comment by quample** [comment]
We have 3 Federation ships done, ranging from lvl1 to lvl 3.

@BenJLubrano should we include more Federation ships? Or should we start working on the Pirate ships?

**Comment by BenJLubrano** [comment]
I would say that we should get at least a couple of pirate ships. If that's what this issue is going to mean then rename it to "new pirate ship designs"

**Comment by BenJLubrano** [comment]
Done for now, may need more later.
