### ISSUE TITLE
Laser beam weapon

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#19]
This weapon will extend in front of the shooter and last for a few seconds. If a ship is in the beam's path, it will take continuous damage.

**Comment by jofebocc** [comment]
[lasers.zip](https://github.com/BenJLubrano/Space-Shooter/files/3756342/lasers.zip)
lasers idea and scketchs

**Comment by jofebocc** [comment]
[laser1animated.zip](https://github.com/BenJLubrano/Space-Shooter/files/3756474/laser1animated.zip)

**Comment by BenJLubrano** [comment]
Attempted this before and it did not work well with our weapon system, but may retry using a different approach in the future. For now, closing this issue.
