### ISSUE TITLE
Create Sprite Sheets & Thruster Animations for Ships

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#32]
Take all of the ships we currently have, add thruster effects to them, and then convert them into sprite sheets.

This issue will be assigned to multiple people since it was decided that each person would do this for their own ships.

**Comment by quample** [comment]
@ricardouseche could you check my branch for this issue and tell me if those sprite sheets are alright.

**Comment by AparnaBudhavarapu** [comment]
I made the suggested changes. @ricardouseche  could you please take a look at my pull request.

**Comment by BenJLubrano** [comment]
This is a heads-up for everyone working on this: Make sure that your sprite sheet has at least 1 frame with no thruster animations.

Currently, since all of animations only have 1 state, the thrusters are always on.

Once a frame without any thrusters is added, just create another 1 frame animation called "idle" or something, and set it so that idle can transition to moving, and moving back to idle.

**Comment by BenJLubrano** [comment]
UPDATE:
All ships should have 4 animations, "Accel", "Decel", "Idle", and "Max Speed".

Idle should obviously be just the frames where the ship has no thruster effects (the ship could still play some animation, but it would be fine if it's just a single frame).

Accel will start with the lowest flame, then it will go to the highest speed.

Max Speed should switch between the two frames with the most thruster flame to the second most flame.

Decel should just be the reverse of Accel, from highest flame all the way to the lowest flame.

**Comment by BenJLubrano** [comment]
As of today, @amathur4 will be making all of the animations. All that everyone else has to do is make sure that your sprite sheet is set up to match all of the specifications of the above comment.

**Comment by BenJLubrano** [comment]
Thruster animations still need to be set up.

**Comment by BenJLubrano** [comment]
done
