### ISSUE TITLE
General Enemies Targeting/Movement Improvements

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#49]
Right now, the ships are not very intelligent with how they shoot. They just shoot forwards if the player is in range, and aim simply by looking at the player.

Ideally, enemies would be able predict where the player goes based on the RigidBody forces of the player and the speed at which the player is moving.

This means that the enemies would shoot towards where the player will be versus where the player is at the moment the shoot.

Also, enemies should not shoot unless they are facing within a few angles of the player, so that way enemies aren't shooting in dumb places (we could just increase the angles at which they consider it a good idea to shoot if we want to make really stupid enemies)

**Comment by quample** [comment]
Would this targeting be exclusive to 
a) specific enemy, eg as the enemy lvl increases, so do their targeting
b) to blaster weapons? I would assume missiles would follow another targeting all together.

**Comment by BenJLubrano** [comment]
We should have a way to make the ship pathing smarter or dumber for different level enemies.

Also, this issue includes fixing weird movement behavior, such as melee ships rotating around the player instead of actually moving towards and attacking them.

**Comment by BenJLubrano** [comment]
Renamed because this issue will also include an animation handler for NPCs

**Comment by BenJLubrano** [comment]
**As of 11/10, here are the things that this branch will include:**

Fix to stop melee enemies from rotating around the target (just decrease their thruster power as they get closer to the player)

Ranged enemies should predict where the player is going to move and fire there instead of at the player

Ranged enemies not shooting unless they are within a certain angle of the player (this is to stop enemies from looking stupid by shooting before they rotate towards the player)

**Some things that would be nice to include in this branch:**

A sort of aggro system where when you hit a ship enough times, it will start attacking you even if your reputation is fine.
For example, if I have 100 reputation and I shoot a federation ship 3-4 times, it should start attacking me, even though my reputation would be down to 97.

This system should also take into account other enemies that have been shooting the ship, and target them based on which one has done the most damage.
Here's an example: A Federation ship is fighting two pirates, a ranged and a melee pirate. The Fed ship is currently shooting the ranged pirate, but the melee one is dealing more damage, so the Fed ship should change targets and kill the more threatening enemy first.

**Comment by BenJLubrano** [comment]
**Additions with this issue**
AggroTable for NPCs, which dictates which targets they attack.
Slightly improved targeting
Melee ships no longer rotate in circles around the player
Enemies don't shoot unless they are within a certain angle of the player

**Notes**
Getting enemies to predict the movement of the player proved to be very difficult, because the player can move in any direction at any time. The NPCs do their best to predict but it isn't much better than before.

**Comment by BenJLubrano** [comment]
done
