### ISSUE TITLE
Space Station Art

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#54]
It would be really cool to have the basic functionality of the space station down by the midterm. This is going to require:

A special UI for the player to interact with.

Art for the space station (likely some simple animations)

Code to support all of this.

This may be split up into multiple issues, but I'm going to assign this one to the "art-work" project.

**Comment by snarla1** [comment]
Will work on the artwork part of spaceship.

@ricardouseche  and @BenJLubrano , Could you confirm the size of the space station art that we are looking at?

**Comment by BenJLubrano** [comment]
Renamed to "Space Station Art" since #64 and #62 exist

**Comment by BenJLubrano** [comment]
Also, the space station should probably be 512x512

**Comment by snarla1** [comment]
Task - add details to the space station.

**Comment by BenJLubrano** [comment]
done
