### ISSUE TITLE
Space Station UI Art

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#62]
We need art to make our Space Station UI look nice. 

The space station is going to be a shop for the player to purchase things from, so it should have tabs with plenty of information about all of this. 

However, for the midterm, the shop should just have the basic layout defined, with buttons for buying items, etc.

**Comment by jofebocc** [comment]
ALmost finishing the SHOP UI and merged the ITEMS

**Comment by jofebocc** [comment]
@BenJLubrano

**Comment by BenJLubrano** [comment]
done
