### ISSUE TITLE
planet 2 boss design

### ISSUE THREAD

**Issue by quample** [BenJLubrano/Space-Shooter#73]
come up with static asset for our planet 2 boss.
Thought it could follow the same color scheme as the planet 1 boss for now.
Naturally the design of the ship should be different.

My initial concept design would be to make a missile cruiser ship, with its attacks primarily being a barrage of missiles.

Would like to work on this, but if anyone else like to take it up, you are welcome to do so.

**Comment by BenJLubrano** [comment]
I like the idea of a boss that shoots a ton of missiles.

**Comment by BenJLubrano** [comment]
done
