### ISSUE TITLE
Parallaxing Improvements

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#90]
There is currently a bug with our parallaxing effects that causes the front layer to jitter when the player rotates.

Additionally, we will need multiple materials, one for each background/foreground effect combo.
This is required because of how unity handles materials, a change in one scene will change the material in all other scenes.

**Comment by ricardouseche** [comment]
I added more materials and reorganized some assets. Couldn't fix the jittering bug however.
