### ISSUE TITLE
Story Intro and Outro Art

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#91]
We need art for our intro story.

The story is as follows:

"In the year 3019, a lone human is transported millions of light years away from Earth after being sucked into a wormhole. The only human in a foreign solar system, they must fend for themselves against the local species, and fight to find a way back home." (Can be changed/reworded as much as desired)

The intro scenes should just be still images (though animations would be cool, they might be a lot of work), and they should show the events from a different perspective than the game, meaning not top down.

**Comment by AparnaBudhavarapu** [comment]
Merged into master
